server:
  port: 80
  servlet:
    context-path: /



mybatis:
  type-aliases-package:



spring:

  thymeleaf:
    cache: false
  datasource:
    data-username: root
    data-password: 983327
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/tmr?useUnicode=true&characterEncoding=utf-8
    type: com.alibaba.druid.pool.DruidDataSource

    schema:
#        - classpath:sql/**


